services:
  memfof-tester:
    build: .
    container_name: memfof-tester
    privileged: true
    ports: #http://127.0.0.1:7861
      - "7861:7861"
    shm_size: 4g
    mem_limit: 8g
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: python3.10 demo.py